### ISSUE TITLE
Paths with spaces are not supported

### ISSUE THREAD

**Issue by ghugues** [wojteklu/xcode-open-on-github#5]
If the source file has a path that contains spaces, this doesn't work.

Solution :
 - Repace all occurrences of `cd $(dirname " & activeDocumentPath & ");` with `cd \"$(dirname '" & activeDocumentPath & "')\";`
 - For "Open on Github", replace `do shell script "open " & githubUrl` with `do shell script "open " & replace_text(githubUrl, " ", "%20")`
 - For "Copy Github link", replace `set the clipboard to githubUrl` with `set the clipboard to replace_text(githubUrl, " ", "%20")`

**Comment by wojteklu** [comment]
Thanks @ghugues! Fixed in https://github.com/wojteklu/xcode-open-on-github/pull/6.

**Comment by mr-fixit** [comment]
This merge didn't make the requested change. Look at the diff, you won't see `\"$(dirname` anywhere.
